#!/usr/bin/env python3
"""Regenerate include/ui/img_lion.h from la-marzocco-lion.svg.

The screensaver's bouncing lion is an LVGL A8 alpha map (shape only, recolored
at draw time — which is also what makes it the "inverted" light-on-dark logo).
The header is COMMITTED because rasterizing needs rsvg-convert (brew install
librsvg); re-run this only when the artwork changes:

    python3 tools/logo/gen_logo.py

Do NOT substitute qlmanage: its thumbnails squash the tall artwork square
(that shipped once — a visibly cut-off lion).
"""

import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
SVG = HERE / "la-marzocco-lion.svg"
OUT = HERE.parent.parent / "include/ui/img_lion.h"
# Sized so the asset's NATIVE height matches the screensaver's target (~40% of a
# 480px-tall screen = ~192px), so the 800x480 boards draw it 1:1 with NO
# transform. A scaled lv_image is markedly more expensive per pixel (~0.77us vs
# ~0.39us for solid fills, measured on the 4.3C), and it also keeps its
# FULL-SIZE layout box, which LVGL invalidates. Boards whose target differs a
# lot (the 2-inch) still scale; see start_screensaver().
WIDTH = 101


def main():
    with tempfile.TemporaryDirectory() as td:
        png = Path(td) / "lion.png"
        subprocess.run(
            ["rsvg-convert", "--height", "1024", "--keep-aspect-ratio",
             "-o", str(png), str(SVG)],
            check=True, capture_output=True)
        im = Image.open(png).convert("RGBA")
    # Alpha map: use the alpha channel when present, else treat dark-on-light.
    a = im.getchannel("A")
    if a.getextrema() == (255, 255):  # opaque render: shape is the dark ink
        a = Image.eval(im.convert("L"), lambda v: 255 - v)
    # Crop to content, then scale to the target width.
    bbox = a.getbbox()
    a = a.crop(bbox)
    h = round(a.height * WIDTH / a.width)
    a = a.resize((WIDTH, h), Image.LANCZOS)
    data = a.tobytes()

    lines = [
        "#pragma once",
        "",
        "// GENERATED by tools/logo/gen_logo.py from tools/logo/la-marzocco-lion.svg",
        "// (committed: regeneration needs rsvg-convert -- `brew install librsvg`;",
        "// NOT qlmanage, which squashes the tall artwork square). A8 alpha map,",
        "// recolored at draw time by the screensaver.",
        "",
        '#include "lvgl.h"',
        "",
        "namespace ui {",
        "",
        f"inline constexpr int kLionW = {WIDTH};",
        f"inline constexpr int kLionH = {h};",
        "",
        f"inline const uint8_t kLionMap[{WIDTH * h}] = {{",
    ]
    for i in range(0, len(data), 24):
        chunk = ",".join(str(b) for b in data[i:i + 24])
        lines.append(f"  {chunk},")
    lines += [
        "};",
        "",
        "// Runtime-built descriptor (avoids nested designated initializers, which",
        "// C++ rejects and LVGL's struct layout makes brittle to hardcode).",
        "inline const lv_image_dsc_t* lion_logo() {",
        "  static lv_image_dsc_t dsc;",
        "  static bool ready = false;",
        "  if (!ready) {",
        "    dsc.header.magic = LV_IMAGE_HEADER_MAGIC;",
        "    dsc.header.cf = LV_COLOR_FORMAT_A8;",
        "    dsc.header.w = kLionW;",
        "    dsc.header.h = kLionH;",
        "    dsc.header.stride = kLionW;",
        "    dsc.data_size = sizeof(kLionMap);",
        "    dsc.data = kLionMap;",
        "    ready = true;",
        "  }",
        "  return &dsc;",
        "}",
        "",
        "}  // namespace ui",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(HERE.parent.parent)} ({WIDTH}x{h}, {len(data)} bytes)")


if __name__ == "__main__":
    main()
