package main

import (
	"crypto/ecdsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"testing"
)

// Cross-checked against pylamarzocco.util.generate_request_proof with the same
// inputs (secret = sha256("test"), base = "abc123.de-ad-be-ef.1700000000000").
func TestRequestProofMatchesPython(t *testing.T) {
	secret := sha256.Sum256([]byte("test"))
	base := "abc123.de-ad-be-ef.1700000000000"
	want := "EkFeu5X5pfL2Az7DFXO2/UoHUSjD+q7ZC3gFJfoqAR0="
	if got := requestProof(base, secret[:]); got != want {
		t.Fatalf("requestProof mismatch:\n got %s\nwant %s", got, want)
	}
}

// Loads a fixed key generated by pylamarzocco and checks that Go derives the
// identical public key, shared secret, base string, and registration proof —
// i.e. the whole registration request payload matches the Python client.
func TestInstallationKeyMatchesPython(t *testing.T) {
	const (
		pkcs8B64 = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfRE6taB8k5U/5Hy50bNLMa9p7cbaT6LV9EAWjTDgixChRANCAAQA9kCp7diFrr48+iDqEPgOo3CIxtYJeoa/JgnsGj65RMT4vnT+qSuKKjN40Xc4psW9NtLSTnwp/g+2EGScH/qP"
		id       = "fixed-install-id-123"
		wantPub  = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAPZAqe3Yha6+PPog6hD4DqNwiMbWCXqGvyYJ7Bo+uUTE+L50/qkriiozeNF3OKbFvTbS0k58Kf4PthBknB/6jw=="
		wantBase = "fixed-install-id-123.I8MCFlkJ6AMd+2conDRwJ6phsxwDLV53n35HfLok2GI="
		wantReg  = "1rqzNodRScwHdepmGY5dztKB8cZLtOgEyyb2zB9fFxI="
	)
	der, err := base64.StdEncoding.DecodeString(pkcs8B64)
	if err != nil {
		t.Fatal(err)
	}
	priv, err := x509.ParsePKCS8PrivateKey(der)
	if err != nil {
		t.Fatal(err)
	}
	k := mustKeyFrom(t, id, priv.(*ecdsa.PrivateKey))

	if got := k.pubB64(); got != wantPub {
		t.Errorf("pubB64 mismatch:\n got %s\nwant %s", got, wantPub)
	}
	if got := k.baseString(); got != wantBase {
		t.Errorf("baseString mismatch:\n got %s\nwant %s", got, wantBase)
	}
	if got := requestProof(k.baseString(), k.secret); got != wantReg {
		t.Errorf("registration proof mismatch:\n got %s\nwant %s", got, wantReg)
	}
}

// mustKeyFrom rebuilds an installationKey around a fixed id + private key,
// deriving pubDER/secret exactly as newInstallationKey does.
func mustKeyFrom(t *testing.T, id string, priv *ecdsa.PrivateKey) *installationKey {
	t.Helper()
	pubDER, err := x509.MarshalPKIXPublicKey(&priv.PublicKey)
	if err != nil {
		t.Fatal(err)
	}
	instHash := sha256.Sum256([]byte(id))
	triple := id + "." + b64(pubDER) + "." + b64(instHash[:])
	secret := sha256.Sum256([]byte(triple))
	return &installationKey{id: id, priv: priv, pubDER: pubDER, secret: secret[:]}
}
