#!/usr/bin/env python3
"""Turn the gzipped single-file web app into a C header (flash-resident)."""
import sys

src, dst = sys.argv[1], sys.argv[2]
data = open(src, 'rb').read()
lines = []
for i in range(0, len(data), 16):
    lines.append('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 16]) + ',')
body = '\n'.join(lines)
open(dst, 'w').write(f"""#pragma once

#include <cstddef>
#include <cstdint>

// GENERATED by tools/webapp/build.sh — do not edit. This is the gzipped
// single-file React app served at '/' (see platform_esp32/web_ui.cpp).
// Rebuild: tools/webapp/build.sh (needs node; the output is committed so
// firmware builds don't).

namespace platform {{

constexpr size_t kWebAppGzLen = {len(data)};
constexpr uint8_t kWebAppGz[] = {{
{body}
}};

}}  // namespace platform
""")
print(f'{dst}: {len(data)} bytes')
